-- Snapshot of the schema produced by backend/migrations (generated by scripts/dump_schema.sh; do not edit).
-- The migrations are the source of truth. Roles are created by db/bootstrap_roles.sql.
--
-- PostgreSQL database dump
--

\restrict 0tF4UX3202nT0IA28KBaTr46KfkaCgkDqWKONiyuPdeIqMQcgn6SYn0mJHxm2cB

-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)


--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- Name: clear_price_floor(uuid); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.clear_price_floor(p_variant uuid) RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
BEGIN
  IF current_business_id() IS NULL THEN RAISE EXCEPTION 'no tenant context'; END IF;
  DELETE FROM price_floors WHERE variant_id = p_variant AND business_id = current_business_id();
END $$;


--
-- Name: current_business_id(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.current_business_id() RETURNS uuid
    LANGUAGE sql STABLE
    AS $$
  SELECT NULLIF(current_setting('app.business_id', true), '')::uuid
$$;


--
-- Name: enable_tenant_rls(regclass, text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.enable_tenant_rls(tbl regclass, col text DEFAULT 'business_id'::text) RETURNS void
    LANGUAGE plpgsql
    AS $$
BEGIN
  EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', tbl);
  EXECUTE format('ALTER TABLE %s FORCE ROW LEVEL SECURITY', tbl);
  EXECUTE format('CREATE POLICY tenant_isolation ON %s USING (%I = current_business_id()) WITH CHECK (%I = current_business_id())', tbl, col, col);
END $$;


--
-- Name: notify_change(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.notify_change() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE conv uuid;
BEGIN
  IF TG_TABLE_NAME = 'conversations' THEN conv := NEW.id;
  ELSIF TG_TABLE_NAME IN ('messages','handoffs','deals') THEN conv := NEW.conversation_id;
  END IF;
  PERFORM pg_notify('salesai_changes', json_build_object('b', NEW.business_id, 't', TG_TABLE_NAME, 'c', conv)::text);
  RETURN NULL;
END $$;


--
-- Name: price_floor_is_set(uuid); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.price_floor_is_set(p_variant uuid) RETURNS boolean
    LANGUAGE plpgsql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
BEGIN
  IF current_business_id() IS NULL THEN RAISE EXCEPTION 'no tenant context'; END IF;
  RETURN EXISTS (SELECT 1 FROM price_floors WHERE variant_id = p_variant AND business_id = current_business_id());
END $$;


--
-- Name: set_price_floor(uuid, numeric); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_price_floor(p_variant uuid, p_floor numeric) RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
BEGIN
  IF current_business_id() IS NULL THEN RAISE EXCEPTION 'no tenant context'; END IF;
  INSERT INTO price_floors (variant_id, business_id, floor_price)
  VALUES (p_variant, current_business_id(), p_floor)
  ON CONFLICT (variant_id) DO UPDATE SET floor_price = EXCLUDED.floor_price, updated_at = now();
END $$;


--
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END $$;




--
-- Name: accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    phone text NOT NULL,
    name text,
    platform_role text,
    status text DEFAULT 'active'::text NOT NULL,
    language text DEFAULT 'en'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_login_at timestamp with time zone,
    signup_source text,
    CONSTRAINT accounts_language_check CHECK ((language = ANY (ARRAY['en'::text, 'hi'::text]))),
    CONSTRAINT accounts_phone_check CHECK ((phone ~ '^\+[1-9][0-9]{7,14}$'::text)),
    CONSTRAINT accounts_platform_role_check CHECK ((platform_role = 'operator'::text)),
    CONSTRAINT accounts_status_check CHECK ((status = ANY (ARRAY['active'::text, 'blocked'::text])))
);

ALTER TABLE ONLY public.accounts FORCE ROW LEVEL SECURITY;


--
-- Name: audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    business_id uuid NOT NULL,
    actor_account_id uuid,
    actor_label text NOT NULL,
    action text NOT NULL,
    entity text NOT NULL,
    entity_id text,
    detail jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.audit_log FORCE ROW LEVEL SECURITY;


--
-- Name: audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: audit_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.audit_log_id_seq OWNED BY public.audit_log.id;


--
-- Name: auth_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_sessions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    account_id uuid NOT NULL,
    business_id uuid,
    family_id uuid NOT NULL,
    refresh_hash text NOT NULL,
    device_label text,
    ip text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_used_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    replaced_by uuid
);


--
-- Name: business_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.business_keys (
    business_id uuid NOT NULL,
    dek_wrapped bytea NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: business_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.business_users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    account_id uuid NOT NULL,
    name text NOT NULL,
    role text DEFAULT 'owner'::text NOT NULL,
    notify boolean DEFAULT true NOT NULL,
    last_inbound_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT business_users_role_check CHECK ((role = ANY (ARRAY['owner'::text, 'staff'::text])))
);

ALTER TABLE ONLY public.business_users FORCE ROW LEVEL SECURITY;


--
-- Name: businesses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.businesses (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    timezone text DEFAULT 'Asia/Kolkata'::text NOT NULL,
    status text DEFAULT 'onboarding'::text NOT NULL,
    ai_enabled boolean DEFAULT false NOT NULL,
    plan text DEFAULT 'pilot'::text NOT NULL,
    profile jsonb DEFAULT '{}'::jsonb NOT NULL,
    sales_settings jsonb DEFAULT '{}'::jsonb NOT NULL,
    conversation_settings jsonb DEFAULT '{}'::jsonb NOT NULL,
    timing_params jsonb DEFAULT '{}'::jsonb NOT NULL,
    limits jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    slug text DEFAULT ('b-'::text || substr(replace((gen_random_uuid())::text, '-'::text, ''::text), 1, 12)) NOT NULL,
    onboarding jsonb DEFAULT '{}'::jsonb NOT NULL,
    signup_source text,
    CONSTRAINT businesses_slug_format CHECK ((slug ~ '^[a-z0-9][a-z0-9-]{1,38}[a-z0-9]$'::text)),
    CONSTRAINT businesses_status_check CHECK ((status = ANY (ARRAY['onboarding'::text, 'active'::text, 'paused'::text, 'churned'::text])))
);

ALTER TABLE ONLY public.businesses FORCE ROW LEVEL SECURITY;


--
-- Name: pricing_policies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pricing_policies (
    variant_id uuid NOT NULL,
    business_id uuid NOT NULL,
    disclosure text NOT NULL,
    currency text DEFAULT 'INR'::text NOT NULL,
    list_price numeric(12,2),
    range_min numeric(12,2),
    range_max numeric(12,2),
    negotiable boolean DEFAULT false NOT NULL,
    ai_may_negotiate boolean DEFAULT false NOT NULL,
    concession_steps integer DEFAULT 0 NOT NULL,
    concession_requires jsonb DEFAULT '[]'::jsonb NOT NULL,
    round_to numeric(12,2) DEFAULT 1 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT pricing_policies_check CHECK (((disclosure <> ALL (ARRAY['fixed'::text, 'starts_from'::text])) OR (list_price IS NOT NULL))),
    CONSTRAINT pricing_policies_check1 CHECK (((disclosure <> 'range'::text) OR ((range_min IS NOT NULL) AND (range_max IS NOT NULL) AND (range_min <= range_max)))),
    CONSTRAINT pricing_policies_check2 CHECK (((NOT negotiable) OR (list_price IS NOT NULL))),
    CONSTRAINT pricing_policies_check3 CHECK (((NOT ai_may_negotiate) OR negotiable)),
    CONSTRAINT pricing_policies_concession_steps_check CHECK ((concession_steps >= 0)),
    CONSTRAINT pricing_policies_currency_check CHECK ((currency ~ '^[A-Z]{3}$'::text)),
    CONSTRAINT pricing_policies_disclosure_check CHECK ((disclosure = ANY (ARRAY['fixed'::text, 'range'::text, 'starts_from'::text, 'after_qualifying'::text, 'on_request'::text]))),
    CONSTRAINT pricing_policies_list_price_check CHECK (((list_price IS NULL) OR (list_price >= (0)::numeric))),
    CONSTRAINT pricing_policies_range_min_check CHECK (((range_min IS NULL) OR (range_min >= (0)::numeric))),
    CONSTRAINT pricing_policies_round_to_check CHECK ((round_to > (0)::numeric))
);

ALTER TABLE ONLY public.pricing_policies FORCE ROW LEVEL SECURITY;


--
-- Name: product_variants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_variants (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    product_id uuid NOT NULL,
    name text DEFAULT 'default'::text NOT NULL,
    attributes jsonb DEFAULT '{}'::jsonb NOT NULL,
    availability text DEFAULT 'in_stock'::text NOT NULL,
    stock_qty integer,
    is_default boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT product_variants_availability_check CHECK ((availability = ANY (ARRAY['in_stock'::text, 'limited'::text, 'made_to_order'::text, 'out_of_stock'::text]))),
    CONSTRAINT product_variants_stock_qty_check CHECK (((stock_qty IS NULL) OR (stock_qty >= 0)))
);

ALTER TABLE ONLY public.product_variants FORCE ROW LEVEL SECURITY;


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    name text NOT NULL,
    description text,
    category text,
    attributes jsonb DEFAULT '{}'::jsonb NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.products FORCE ROW LEVEL SECURITY;


--
-- Name: catalog_public; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.catalog_public WITH (security_invoker='true') AS
 SELECT v.business_id,
    p.id AS product_id,
    p.name AS product_name,
    p.description,
    p.category,
    p.attributes AS product_attributes,
    v.id AS variant_id,
    v.name AS variant_name,
    v.attributes,
    v.availability,
    v.stock_qty,
    pp.disclosure,
    pp.currency,
    pp.list_price,
    pp.range_min,
    pp.range_max,
    pp.negotiable,
    v.is_default,
    (( SELECT count(*) AS count
           FROM public.product_variants x
          WHERE ((x.product_id = p.id) AND (x.business_id = p.business_id) AND x.active)))::integer AS variant_count
   FROM ((public.product_variants v
     JOIN public.products p ON (((p.business_id = v.business_id) AND (p.id = v.product_id))))
     JOIN public.pricing_policies pp ON (((pp.business_id = v.business_id) AND (pp.variant_id = v.id))))
  WHERE (p.active AND v.active);


--
-- Name: config_proposals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.config_proposals (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    business_user_id uuid NOT NULL,
    summary text NOT NULL,
    changes jsonb NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    decided_at timestamp with time zone,
    CONSTRAINT config_proposals_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'applied'::text, 'cancelled'::text, 'expired'::text])))
);

ALTER TABLE ONLY public.config_proposals FORCE ROW LEVEL SECURITY;


--
-- Name: conversations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.conversations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    customer_id uuid NOT NULL,
    whatsapp_number_id uuid NOT NULL,
    state text DEFAULT 'idle'::text NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    lead_stage text DEFAULT 'new'::text NOT NULL,
    lost_reason text,
    qualification jsonb DEFAULT '{}'::jsonb NOT NULL,
    summary text,
    summary_upto timestamp with time zone,
    ai_paused_until timestamp with time zone,
    ai_paused_reason text,
    selling_stopped boolean DEFAULT false NOT NULL,
    nudge_sent_at timestamp with time zone,
    last_inbound_at timestamp with time zone,
    last_outbound_at timestamp with time zone,
    last_owner_reply_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT conversations_lead_stage_check CHECK ((lead_stage = ANY (ARRAY['new'::text, 'exploring'::text, 'interested'::text, 'negotiating'::text, 'ready_to_buy'::text, 'won'::text, 'lost'::text]))),
    CONSTRAINT conversations_state_check CHECK ((state = ANY (ARRAY['idle'::text, 'listening'::text, 'deciding'::text, 'composing'::text, 'typing'::text])))
);

ALTER TABLE ONLY public.conversations FORCE ROW LEVEL SECURITY;


--
-- Name: customers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customers (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    wa_id text NOT NULL,
    name text,
    profile jsonb DEFAULT '{}'::jsonb NOT NULL,
    is_personal boolean DEFAULT false NOT NULL,
    opted_out boolean DEFAULT false NOT NULL,
    opted_out_at timestamp with time zone,
    first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    last_seen_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.customers FORCE ROW LEVEL SECURITY;


--
-- Name: deals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.deals (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    conversation_id uuid NOT NULL,
    kind text NOT NULL,
    items jsonb DEFAULT '[]'::jsonb NOT NULL,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    value numeric(12,2),
    status text DEFAULT 'pending'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    closed_at timestamp with time zone,
    closed_by uuid,
    CONSTRAINT deals_kind_check CHECK ((kind = ANY (ARRAY['order'::text, 'visit'::text]))),
    CONSTRAINT deals_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'won'::text, 'lost'::text])))
);

ALTER TABLE ONLY public.deals FORCE ROW LEVEL SECURITY;


--
-- Name: handoffs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.handoffs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    conversation_id uuid NOT NULL,
    reason text NOT NULL,
    note text,
    status text DEFAULT 'open'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    resolved_at timestamp with time zone,
    resolved_by uuid,
    CONSTRAINT handoffs_reason_check CHECK ((reason = ANY (ARRAY['unknown_answer'::text, 'on_request_price'::text, 'below_floor'::text, 'customer_asked_human'::text, 'complaint'::text, 'high_value'::text, 'system_failure'::text, 'other'::text]))),
    CONSTRAINT handoffs_status_check CHECK ((status = ANY (ARRAY['open'::text, 'resolved'::text])))
);

ALTER TABLE ONLY public.handoffs FORCE ROW LEVEL SECURITY;


--
-- Name: idempotency_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.idempotency_keys (
    business_id uuid NOT NULL,
    key text NOT NULL,
    request_hash text NOT NULL,
    status integer NOT NULL,
    response jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.idempotency_keys FORCE ROW LEVEL SECURITY;


--
-- Name: invoice_number_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.invoice_number_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: invoices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invoices (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    number text NOT NULL,
    status text DEFAULT 'open'::text NOT NULL,
    plan text NOT NULL,
    billing_interval text DEFAULT 'month'::text NOT NULL,
    period_start timestamp with time zone NOT NULL,
    period_end timestamp with time zone NOT NULL,
    lines jsonb NOT NULL,
    subtotal_paise bigint NOT NULL,
    gst_paise bigint NOT NULL,
    total_paise bigint NOT NULL,
    currency text DEFAULT 'INR'::text NOT NULL,
    issued_at timestamp with time zone DEFAULT now() NOT NULL,
    due_at timestamp with time zone NOT NULL,
    paid_at timestamp with time zone,
    CONSTRAINT invoices_billing_interval_check CHECK ((billing_interval = ANY (ARRAY['month'::text, 'year'::text]))),
    CONSTRAINT invoices_gst_paise_check CHECK ((gst_paise >= 0)),
    CONSTRAINT invoices_status_check CHECK ((status = ANY (ARRAY['open'::text, 'paid'::text, 'void'::text]))),
    CONSTRAINT invoices_subtotal_paise_check CHECK ((subtotal_paise >= 0)),
    CONSTRAINT invoices_total_paise_check CHECK ((total_paise >= 0))
);

ALTER TABLE ONLY public.invoices FORCE ROW LEVEL SECURITY;


--
-- Name: jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.jobs (
    id bigint NOT NULL,
    queue text NOT NULL,
    kind text NOT NULL,
    business_id uuid,
    ordering_key text,
    entity_key text,
    entity_version bigint,
    dedupe_key text,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    run_at timestamp with time zone DEFAULT now() NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    max_attempts integer DEFAULT 5 NOT NULL,
    last_error text,
    locked_by text,
    lease_until timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    finished_at timestamp with time zone,
    CONSTRAINT jobs_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'running'::text, 'done'::text, 'cancelled'::text, 'dead'::text])))
);


--
-- Name: jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: jobs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.jobs_id_seq OWNED BY public.jobs.id;


--
-- Name: knowledge_gaps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.knowledge_gaps (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    conversation_id uuid,
    question text NOT NULL,
    answer text,
    status text DEFAULT 'open'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    answered_at timestamp with time zone,
    CONSTRAINT knowledge_gaps_status_check CHECK ((status = ANY (ARRAY['open'::text, 'answered'::text, 'dismissed'::text])))
);

ALTER TABLE ONLY public.knowledge_gaps FORCE ROW LEVEL SECURITY;


--
-- Name: messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messages (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    conversation_id uuid NOT NULL,
    turn_id uuid,
    wa_message_id text,
    direction text NOT NULL,
    sender text NOT NULL,
    kind text DEFAULT 'text'::text NOT NULL,
    body text,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    reply_to_wa_id text,
    status text DEFAULT 'received'::text NOT NULL,
    error text,
    gap_ms integer,
    answered boolean DEFAULT false NOT NULL,
    wa_timestamp timestamp with time zone,
    sent_at timestamp with time zone,
    delivered_at timestamp with time zone,
    read_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT messages_direction_check CHECK ((direction = ANY (ARRAY['in'::text, 'out'::text]))),
    CONSTRAINT messages_kind_check CHECK ((kind = ANY (ARRAY['text'::text, 'audio'::text, 'image'::text, 'reaction'::text, 'template'::text, 'other'::text]))),
    CONSTRAINT messages_sender_check CHECK ((sender = ANY (ARRAY['customer'::text, 'ai'::text, 'owner'::text, 'system'::text]))),
    CONSTRAINT messages_status_check CHECK ((status = ANY (ARRAY['received'::text, 'queued'::text, 'sent'::text, 'delivered'::text, 'read'::text, 'failed'::text, 'cancelled'::text])))
);

ALTER TABLE ONLY public.messages FORCE ROW LEVEL SECURITY;


--
-- Name: negotiations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.negotiations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    conversation_id uuid NOT NULL,
    variant_id uuid NOT NULL,
    quantity integer DEFAULT 1 NOT NULL,
    current_offer numeric(12,2),
    customer_best numeric(12,2),
    step integer DEFAULT 0 NOT NULL,
    held_below_floor boolean DEFAULT false NOT NULL,
    status text DEFAULT 'open'::text NOT NULL,
    history jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT negotiations_quantity_check CHECK ((quantity > 0)),
    CONSTRAINT negotiations_status_check CHECK ((status = ANY (ARRAY['open'::text, 'agreed'::text, 'declined'::text, 'handed_off'::text])))
);

ALTER TABLE ONLY public.negotiations FORCE ROW LEVEL SECURITY;


--
-- Name: offers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.offers (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    variant_id uuid,
    name text NOT NULL,
    kind text NOT NULL,
    value numeric(12,2),
    free_item text,
    conditions jsonb DEFAULT '{}'::jsonb NOT NULL,
    starts_at timestamp with time zone,
    ends_at timestamp with time zone,
    may_cross_floor boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT offers_check CHECK (((ends_at IS NULL) OR (starts_at IS NULL) OR (ends_at > starts_at))),
    CONSTRAINT offers_check1 CHECK (((kind <> ALL (ARRAY['percent'::text, 'flat'::text])) OR (value IS NOT NULL))),
    CONSTRAINT offers_check2 CHECK (((kind <> 'percent'::text) OR (value <= (100)::numeric))),
    CONSTRAINT offers_kind_check CHECK ((kind = ANY (ARRAY['percent'::text, 'flat'::text, 'bundle'::text, 'free_item'::text]))),
    CONSTRAINT offers_value_check CHECK (((value IS NULL) OR (value >= (0)::numeric)))
);

ALTER TABLE ONLY public.offers FORCE ROW LEVEL SECURITY;


--
-- Name: operator_alerts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.operator_alerts (
    id bigint NOT NULL,
    business_id uuid,
    severity text DEFAULT 'warning'::text NOT NULL,
    kind text NOT NULL,
    message text NOT NULL,
    detail jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    resolved_at timestamp with time zone,
    notified_at timestamp with time zone,
    notify_attempts integer DEFAULT 0 NOT NULL,
    notify_error text,
    CONSTRAINT operator_alerts_severity_check CHECK ((severity = ANY (ARRAY['info'::text, 'warning'::text, 'critical'::text])))
);


--
-- Name: operator_alerts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.operator_alerts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: operator_alerts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.operator_alerts_id_seq OWNED BY public.operator_alerts.id;


--
-- Name: otp_challenges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.otp_challenges (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    phone text NOT NULL,
    code_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    consumed_at timestamp with time zone,
    ip text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: outbox; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.outbox (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid,
    event_type text NOT NULL,
    schema_version integer DEFAULT 1 NOT NULL,
    ordering_key text,
    entity_key text,
    entity_version bigint,
    run_at timestamp with time zone DEFAULT now() NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    occurred_at timestamp with time zone DEFAULT now() NOT NULL,
    published_at timestamp with time zone,
    seq bigint NOT NULL
);

ALTER TABLE ONLY public.outbox FORCE ROW LEVEL SECURITY;


--
-- Name: outbox_seq_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.outbox_seq_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: outbox_seq_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.outbox_seq_seq OWNED BY public.outbox.seq;


--
-- Name: owner_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.owner_messages (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    business_user_id uuid NOT NULL,
    direction text NOT NULL,
    kind text DEFAULT 'text'::text NOT NULL,
    purpose text DEFAULT 'chat'::text NOT NULL,
    template_name text,
    body text,
    wa_message_id text,
    status text DEFAULT 'received'::text NOT NULL,
    error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    sent_at timestamp with time zone,
    CONSTRAINT owner_messages_direction_check CHECK ((direction = ANY (ARRAY['in'::text, 'out'::text]))),
    CONSTRAINT owner_messages_kind_check CHECK ((kind = ANY (ARRAY['text'::text, 'template'::text, 'audio'::text, 'other'::text]))),
    CONSTRAINT owner_messages_purpose_check CHECK ((purpose = ANY (ARRAY['chat'::text, 'handoff_alert'::text, 'daily_summary'::text, 'deal_alert'::text, 'disconnect_alert'::text, 'setup'::text, 'otp'::text]))),
    CONSTRAINT owner_messages_status_check CHECK ((status = ANY (ARRAY['received'::text, 'queued'::text, 'sent'::text, 'delivered'::text, 'read'::text, 'failed'::text])))
);

ALTER TABLE ONLY public.owner_messages FORCE ROW LEVEL SECURITY;


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    invoice_id uuid NOT NULL,
    provider text NOT NULL,
    provider_ref text NOT NULL,
    amount_paise bigint NOT NULL,
    status text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT payments_amount_paise_check CHECK ((amount_paise >= 0)),
    CONSTRAINT payments_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'succeeded'::text, 'failed'::text])))
);

ALTER TABLE ONLY public.payments FORCE ROW LEVEL SECURITY;


--
-- Name: price_floors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.price_floors (
    variant_id uuid NOT NULL,
    business_id uuid NOT NULL,
    floor_price numeric(12,2) NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT price_floors_floor_price_check CHECK ((floor_price >= (0)::numeric))
);

ALTER TABLE ONLY public.price_floors FORCE ROW LEVEL SECURITY;


--
-- Name: rate_buckets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rate_buckets (
    key text NOT NULL,
    tokens double precision NOT NULL,
    updated_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version text NOT NULL,
    checksum text NOT NULL,
    applied_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: sim_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sim_messages (
    id bigint NOT NULL,
    phone text NOT NULL,
    business_phone text NOT NULL,
    direction text NOT NULL,
    kind text DEFAULT 'text'::text NOT NULL,
    body text,
    template_name text,
    wa_message_id text,
    reaction_to text,
    status text DEFAULT 'sent'::text NOT NULL,
    typing boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT sim_messages_direction_check CHECK ((direction = ANY (ARRAY['to_user'::text, 'from_user'::text])))
);


--
-- Name: sim_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sim_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sim_messages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sim_messages_id_seq OWNED BY public.sim_messages.id;


--
-- Name: style_examples; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.style_examples (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    situation text NOT NULL,
    customer_text text,
    owner_reply text NOT NULL,
    source text DEFAULT 'manual'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT style_examples_source_check CHECK ((source = ANY (ARRAY['manual'::text, 'learned'::text])))
);

ALTER TABLE ONLY public.style_examples FORCE ROW LEVEL SECURITY;


--
-- Name: subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subscriptions (
    business_id uuid NOT NULL,
    plan text NOT NULL,
    status text NOT NULL,
    billing_interval text DEFAULT 'month'::text NOT NULL,
    trial_ends_at timestamp with time zone,
    current_period_start timestamp with time zone,
    current_period_end timestamp with time zone,
    cancel_at_period_end boolean DEFAULT false NOT NULL,
    pending_plan text,
    pending_interval text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT subscriptions_billing_interval_check CHECK ((billing_interval = ANY (ARRAY['month'::text, 'year'::text]))),
    CONSTRAINT subscriptions_pending_interval_check CHECK ((pending_interval = ANY (ARRAY['month'::text, 'year'::text]))),
    CONSTRAINT subscriptions_status_check CHECK ((status = ANY (ARRAY['trialing'::text, 'active'::text, 'past_due'::text, 'canceled'::text, 'pilot'::text])))
);

ALTER TABLE ONLY public.subscriptions FORCE ROW LEVEL SECURITY;


--
-- Name: turns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.turns (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    conversation_id uuid NOT NULL,
    conversation_version bigint NOT NULL,
    inbound_message_ids uuid[] DEFAULT '{}'::uuid[] NOT NULL,
    status text DEFAULT 'planned'::text NOT NULL,
    decision jsonb DEFAULT '{}'::jsonb NOT NULL,
    signals jsonb DEFAULT '{}'::jsonb NOT NULL,
    model text,
    prompt_versions jsonb DEFAULT '{}'::jsonb NOT NULL,
    input_tokens integer,
    output_tokens integer,
    cost_micros bigint,
    latency_ms integer,
    error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone,
    CONSTRAINT turns_status_check CHECK ((status = ANY (ARRAY['planned'::text, 'sent'::text, 'cancelled'::text, 'failed'::text])))
);

ALTER TABLE ONLY public.turns FORCE ROW LEVEL SECURITY;


--
-- Name: webhook_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.webhook_events (
    id bigint NOT NULL,
    received_at timestamp with time zone DEFAULT now() NOT NULL,
    source text DEFAULT 'whatsapp_cloud'::text NOT NULL,
    signature_valid boolean NOT NULL,
    payload jsonb NOT NULL,
    processed_at timestamp with time zone,
    error text
);


--
-- Name: webhook_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.webhook_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: webhook_events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.webhook_events_id_seq OWNED BY public.webhook_events.id;


--
-- Name: whatsapp_numbers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.whatsapp_numbers (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    business_id uuid NOT NULL,
    channel text DEFAULT 'whatsapp_cloud'::text NOT NULL,
    phone_number_id text NOT NULL,
    waba_id text NOT NULL,
    display_phone text NOT NULL,
    verified_name text,
    access_token_enc bytea,
    coexistence boolean DEFAULT false NOT NULL,
    status text DEFAULT 'connected'::text NOT NULL,
    quality_rating text,
    status_reason text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT whatsapp_numbers_channel_check CHECK ((channel = ANY (ARRAY['whatsapp_cloud'::text, 'simulator'::text]))),
    CONSTRAINT whatsapp_numbers_quality_rating_check CHECK ((quality_rating = ANY (ARRAY['green'::text, 'yellow'::text, 'red'::text]))),
    CONSTRAINT whatsapp_numbers_status_check CHECK ((status = ANY (ARRAY['connected'::text, 'disconnected'::text, 'restricted'::text])))
);

ALTER TABLE ONLY public.whatsapp_numbers FORCE ROW LEVEL SECURITY;


--
-- Name: audit_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log ALTER COLUMN id SET DEFAULT nextval('public.audit_log_id_seq'::regclass);


--
-- Name: jobs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs ALTER COLUMN id SET DEFAULT nextval('public.jobs_id_seq'::regclass);


--
-- Name: operator_alerts id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operator_alerts ALTER COLUMN id SET DEFAULT nextval('public.operator_alerts_id_seq'::regclass);


--
-- Name: outbox seq; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.outbox ALTER COLUMN seq SET DEFAULT nextval('public.outbox_seq_seq'::regclass);


--
-- Name: sim_messages id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sim_messages ALTER COLUMN id SET DEFAULT nextval('public.sim_messages_id_seq'::regclass);


--
-- Name: webhook_events id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.webhook_events ALTER COLUMN id SET DEFAULT nextval('public.webhook_events_id_seq'::regclass);


--
-- Name: accounts accounts_phone_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_phone_key UNIQUE (phone);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);


--
-- Name: auth_sessions auth_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT auth_sessions_pkey PRIMARY KEY (id);


--
-- Name: auth_sessions auth_sessions_refresh_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT auth_sessions_refresh_hash_key UNIQUE (refresh_hash);


--
-- Name: business_keys business_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_keys
    ADD CONSTRAINT business_keys_pkey PRIMARY KEY (business_id);


--
-- Name: business_users business_users_business_id_account_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_users
    ADD CONSTRAINT business_users_business_id_account_id_key UNIQUE (business_id, account_id);


--
-- Name: business_users business_users_business_id_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_users
    ADD CONSTRAINT business_users_business_id_id_key UNIQUE (business_id, id);


--
-- Name: business_users business_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_users
    ADD CONSTRAINT business_users_pkey PRIMARY KEY (id);


--
-- Name: businesses businesses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.businesses
    ADD CONSTRAINT businesses_pkey PRIMARY KEY (id);


--
-- Name: config_proposals config_proposals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.config_proposals
    ADD CONSTRAINT config_proposals_pkey PRIMARY KEY (id);


--
-- Name: conversations conversations_business_id_customer_id_whatsapp_number_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT conversations_business_id_customer_id_whatsapp_number_id_key UNIQUE (business_id, customer_id, whatsapp_number_id);


--
-- Name: conversations conversations_business_id_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT conversations_business_id_id_key UNIQUE (business_id, id);


--
-- Name: conversations conversations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT conversations_pkey PRIMARY KEY (id);


--
-- Name: customers customers_business_id_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_business_id_id_key UNIQUE (business_id, id);


--
-- Name: customers customers_business_id_wa_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_business_id_wa_id_key UNIQUE (business_id, wa_id);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- Name: deals deals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deals
    ADD CONSTRAINT deals_pkey PRIMARY KEY (id);


--
-- Name: handoffs handoffs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.handoffs
    ADD CONSTRAINT handoffs_pkey PRIMARY KEY (id);


--
-- Name: idempotency_keys idempotency_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idempotency_keys
    ADD CONSTRAINT idempotency_keys_pkey PRIMARY KEY (business_id, key);


--
-- Name: invoices invoices_business_id_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_business_id_id_key UNIQUE (business_id, id);


--
-- Name: invoices invoices_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_number_key UNIQUE (number);


--
-- Name: invoices invoices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_pkey PRIMARY KEY (id);


--
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);


--
-- Name: knowledge_gaps knowledge_gaps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_gaps
    ADD CONSTRAINT knowledge_gaps_pkey PRIMARY KEY (id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: messages messages_wa_message_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_wa_message_id_key UNIQUE (wa_message_id);


--
-- Name: negotiations negotiations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.negotiations
    ADD CONSTRAINT negotiations_pkey PRIMARY KEY (id);


--
-- Name: offers offers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_pkey PRIMARY KEY (id);


--
-- Name: operator_alerts operator_alerts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operator_alerts
    ADD CONSTRAINT operator_alerts_pkey PRIMARY KEY (id);


--
-- Name: otp_challenges otp_challenges_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.otp_challenges
    ADD CONSTRAINT otp_challenges_pkey PRIMARY KEY (id);


--
-- Name: outbox outbox_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.outbox
    ADD CONSTRAINT outbox_pkey PRIMARY KEY (id);


--
-- Name: owner_messages owner_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.owner_messages
    ADD CONSTRAINT owner_messages_pkey PRIMARY KEY (id);


--
-- Name: owner_messages owner_messages_wa_message_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.owner_messages
    ADD CONSTRAINT owner_messages_wa_message_id_key UNIQUE (wa_message_id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: payments payments_provider_provider_ref_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_provider_provider_ref_key UNIQUE (provider, provider_ref);


--
-- Name: price_floors price_floors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.price_floors
    ADD CONSTRAINT price_floors_pkey PRIMARY KEY (variant_id);


--
-- Name: pricing_policies pricing_policies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pricing_policies
    ADD CONSTRAINT pricing_policies_pkey PRIMARY KEY (variant_id);


--
-- Name: product_variants product_variants_business_id_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_variants
    ADD CONSTRAINT product_variants_business_id_id_key UNIQUE (business_id, id);


--
-- Name: product_variants product_variants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_variants
    ADD CONSTRAINT product_variants_pkey PRIMARY KEY (id);


--
-- Name: products products_business_id_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_business_id_id_key UNIQUE (business_id, id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: rate_buckets rate_buckets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rate_buckets
    ADD CONSTRAINT rate_buckets_pkey PRIMARY KEY (key);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: sim_messages sim_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sim_messages
    ADD CONSTRAINT sim_messages_pkey PRIMARY KEY (id);


--
-- Name: sim_messages sim_messages_wa_message_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sim_messages
    ADD CONSTRAINT sim_messages_wa_message_id_key UNIQUE (wa_message_id);


--
-- Name: style_examples style_examples_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.style_examples
    ADD CONSTRAINT style_examples_pkey PRIMARY KEY (id);


--
-- Name: subscriptions subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_pkey PRIMARY KEY (business_id);


--
-- Name: turns turns_business_id_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turns
    ADD CONSTRAINT turns_business_id_id_key UNIQUE (business_id, id);


--
-- Name: turns turns_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turns
    ADD CONSTRAINT turns_pkey PRIMARY KEY (id);


--
-- Name: webhook_events webhook_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.webhook_events
    ADD CONSTRAINT webhook_events_pkey PRIMARY KEY (id);


--
-- Name: whatsapp_numbers whatsapp_numbers_business_id_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.whatsapp_numbers
    ADD CONSTRAINT whatsapp_numbers_business_id_id_key UNIQUE (business_id, id);


--
-- Name: whatsapp_numbers whatsapp_numbers_phone_number_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.whatsapp_numbers
    ADD CONSTRAINT whatsapp_numbers_phone_number_id_key UNIQUE (phone_number_id);


--
-- Name: whatsapp_numbers whatsapp_numbers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.whatsapp_numbers
    ADD CONSTRAINT whatsapp_numbers_pkey PRIMARY KEY (id);


--
-- Name: audit_biz_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_biz_idx ON public.audit_log USING btree (business_id, created_at DESC);


--
-- Name: auth_sessions_account_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_sessions_account_idx ON public.auth_sessions USING btree (account_id, revoked_at);


--
-- Name: auth_sessions_family_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_sessions_family_idx ON public.auth_sessions USING btree (family_id);


--
-- Name: businesses_slug_uq; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX businesses_slug_uq ON public.businesses USING btree (slug);


--
-- Name: config_proposals_one_pending; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX config_proposals_one_pending ON public.config_proposals USING btree (business_id, business_user_id) WHERE (status = 'pending'::text);


--
-- Name: conversations_list_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX conversations_list_idx ON public.conversations USING btree (business_id, whatsapp_number_id, updated_at DESC);


--
-- Name: deals_biz_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX deals_biz_idx ON public.deals USING btree (business_id, status, created_at DESC);


--
-- Name: handoffs_open_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX handoffs_open_idx ON public.handoffs USING btree (business_id, status, created_at DESC);


--
-- Name: invoices_business_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX invoices_business_idx ON public.invoices USING btree (business_id, issued_at DESC);


--
-- Name: jobs_dead_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX jobs_dead_idx ON public.jobs USING btree (queue, finished_at) WHERE (status = 'dead'::text);


--
-- Name: jobs_dedupe_uq; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX jobs_dedupe_uq ON public.jobs USING btree (queue, dedupe_key) WHERE (dedupe_key IS NOT NULL);


--
-- Name: jobs_due_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX jobs_due_idx ON public.jobs USING btree (queue, run_at) WHERE (status = 'pending'::text);


--
-- Name: jobs_entity_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX jobs_entity_idx ON public.jobs USING btree (entity_key) WHERE (status = 'pending'::text);


--
-- Name: jobs_lease_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX jobs_lease_idx ON public.jobs USING btree (lease_until) WHERE (status = 'running'::text);


--
-- Name: jobs_orderkey_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX jobs_orderkey_idx ON public.jobs USING btree (queue, ordering_key, run_at, id) WHERE ((status = 'pending'::text) AND (ordering_key IS NOT NULL));


--
-- Name: jobs_running_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX jobs_running_idx ON public.jobs USING btree (queue, ordering_key) WHERE (status = 'running'::text);


--
-- Name: messages_conv_time_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX messages_conv_time_idx ON public.messages USING btree (business_id, conversation_id, created_at);


--
-- Name: messages_out_time_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX messages_out_time_idx ON public.messages USING btree (business_id, created_at) WHERE (direction = 'out'::text);


--
-- Name: messages_unanswered_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX messages_unanswered_idx ON public.messages USING btree (business_id, conversation_id) WHERE ((direction = 'in'::text) AND (NOT answered));


--
-- Name: negotiations_one_open_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX negotiations_one_open_idx ON public.negotiations USING btree (business_id, conversation_id, variant_id) WHERE (status = 'open'::text);


--
-- Name: offers_biz_id_uq; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX offers_biz_id_uq ON public.offers USING btree (business_id, id);


--
-- Name: operator_alerts_due_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX operator_alerts_due_idx ON public.operator_alerts USING btree (id) WHERE (resolved_at IS NULL);


--
-- Name: otp_ip_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX otp_ip_idx ON public.otp_challenges USING btree (ip, created_at DESC);


--
-- Name: otp_phone_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX otp_phone_idx ON public.otp_challenges USING btree (phone, created_at DESC);


--
-- Name: outbox_unpublished_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX outbox_unpublished_idx ON public.outbox USING btree (seq) WHERE (published_at IS NULL);


--
-- Name: owner_messages_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX owner_messages_idx ON public.owner_messages USING btree (business_id, business_user_id, created_at DESC);


--
-- Name: products_biz_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX products_biz_idx ON public.products USING btree (business_id, active);


--
-- Name: products_name_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX products_name_trgm ON public.products USING gin ((((((name || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || COALESCE(category, ''::text))) public.gin_trgm_ops);


--
-- Name: sim_messages_phone_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sim_messages_phone_idx ON public.sim_messages USING btree (phone, business_phone, id);


--
-- Name: turns_biz_time_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX turns_biz_time_idx ON public.turns USING btree (business_id, created_at);


--
-- Name: turns_conv_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX turns_conv_idx ON public.turns USING btree (business_id, conversation_id, created_at DESC);


--
-- Name: variants_product_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX variants_product_idx ON public.product_variants USING btree (business_id, product_id);


--
-- Name: webhook_events_recv_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX webhook_events_recv_idx ON public.webhook_events USING btree (received_at);


--
-- Name: businesses businesses_updated; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER businesses_updated BEFORE UPDATE ON public.businesses FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: conversations conversations_notify; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER conversations_notify AFTER INSERT OR UPDATE ON public.conversations FOR EACH ROW EXECUTE FUNCTION public.notify_change();


--
-- Name: conversations conversations_updated; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER conversations_updated BEFORE UPDATE ON public.conversations FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: deals deals_notify; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER deals_notify AFTER INSERT OR UPDATE ON public.deals FOR EACH ROW EXECUTE FUNCTION public.notify_change();


--
-- Name: price_floors floors_updated; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER floors_updated BEFORE UPDATE ON public.price_floors FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: knowledge_gaps gaps_notify; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER gaps_notify AFTER INSERT OR UPDATE ON public.knowledge_gaps FOR EACH ROW EXECUTE FUNCTION public.notify_change();


--
-- Name: handoffs handoffs_notify; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER handoffs_notify AFTER INSERT OR UPDATE ON public.handoffs FOR EACH ROW EXECUTE FUNCTION public.notify_change();


--
-- Name: messages messages_notify; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER messages_notify AFTER INSERT OR UPDATE ON public.messages FOR EACH ROW EXECUTE FUNCTION public.notify_change();


--
-- Name: negotiations negotiations_updated; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER negotiations_updated BEFORE UPDATE ON public.negotiations FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: pricing_policies pricing_updated; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER pricing_updated BEFORE UPDATE ON public.pricing_policies FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: products products_updated; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER products_updated BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: subscriptions subscriptions_touch; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER subscriptions_touch BEFORE UPDATE ON public.subscriptions FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: whatsapp_numbers wa_numbers_updated; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER wa_numbers_updated BEFORE UPDATE ON public.whatsapp_numbers FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: audit_log audit_log_business_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;


--
-- Name: auth_sessions auth_sessions_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT auth_sessions_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;


--
-- Name: auth_sessions auth_sessions_business_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT auth_sessions_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;


--
-- Name: business_keys business_keys_business_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_keys
    ADD CONSTRAINT business_keys_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;


--
-- Name: business_users business_users_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_users
    ADD CONSTRAINT business_users_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;


--
-- Name: business_users business_users_business_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_users
    ADD CONSTRAINT business_users_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;


--
-- Name: config_proposals config_proposals_business_id_business_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.config_proposals
    ADD CONSTRAINT config_proposals_business_id_business_user_id_fkey FOREIGN KEY (business_id, business_user_id) REFERENCES public.business_users(business_id, id) ON DELETE CASCADE;


--
-- Name: conversations conversations_business_id_customer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT conversations_business_id_customer_id_fkey FOREIGN KEY (business_id, customer_id) REFERENCES public.customers(business_id, id) ON DELETE CASCADE;


--
-- Name: conversations conversations_business_id_whatsapp_number_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT conversations_business_id_whatsapp_number_id_fkey FOREIGN KEY (business_id, whatsapp_number_id) REFERENCES public.whatsapp_numbers(business_id, id) ON DELETE CASCADE;


--
-- Name: customers customers_business_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;


--
-- Name: deals deals_business_id_conversation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deals
    ADD CONSTRAINT deals_business_id_conversation_id_fkey FOREIGN KEY (business_id, conversation_id) REFERENCES public.conversations(business_id, id) ON DELETE CASCADE;


--
-- Name: handoffs handoffs_business_id_conversation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.handoffs
    ADD CONSTRAINT handoffs_business_id_conversation_id_fkey FOREIGN KEY (business_id, conversation_id) REFERENCES public.conversations(business_id, id) ON DELETE CASCADE;


--
-- Name: idempotency_keys idempotency_keys_business_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.idempotency_keys
    ADD CONSTRAINT idempotency_keys_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;


--
-- Name: invoices invoices_business_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;


--
-- Name: knowledge_gaps knowledge_gaps_business_id_conversation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_gaps
    ADD CONSTRAINT knowledge_gaps_business_id_conversation_id_fkey FOREIGN KEY (business_id, conversation_id) REFERENCES public.conversations(business_id, id) ON DELETE SET NULL (conversation_id);


--
-- Name: knowledge_gaps knowledge_gaps_business_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_gaps
    ADD CONSTRAINT knowledge_gaps_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;


--
-- Name: messages messages_business_id_conversation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_business_id_conversation_id_fkey FOREIGN KEY (business_id, conversation_id) REFERENCES public.conversations(business_id, id) ON DELETE CASCADE;


--
-- Name: messages messages_business_id_turn_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_business_id_turn_id_fkey FOREIGN KEY (business_id, turn_id) REFERENCES public.turns(business_id, id) ON DELETE SET NULL (turn_id);


--
-- Name: negotiations negotiations_business_id_conversation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.negotiations
    ADD CONSTRAINT negotiations_business_id_conversation_id_fkey FOREIGN KEY (business_id, conversation_id) REFERENCES public.conversations(business_id, id) ON DELETE CASCADE;


--
-- Name: negotiations negotiations_business_id_variant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.negotiations
    ADD CONSTRAINT negotiations_business_id_variant_id_fkey FOREIGN KEY (business_id, variant_id) REFERENCES public.product_variants(business_id, id) ON DELETE CASCADE;


--
-- Name: offers offers_business_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;


--
-- Name: offers offers_business_id_variant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_business_id_variant_id_fkey FOREIGN KEY (business_id, variant_id) REFERENCES public.product_variants(business_id, id) ON DELETE CASCADE;


--
-- Name: operator_alerts operator_alerts_business_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operator_alerts
    ADD CONSTRAINT operator_alerts_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;


--
-- Name: owner_messages owner_messages_business_id_business_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.owner_messages
    ADD CONSTRAINT owner_messages_business_id_business_user_id_fkey FOREIGN KEY (business_id, business_user_id) REFERENCES public.business_users(business_id, id) ON DELETE CASCADE;


--
-- Name: payments payments_business_id_invoice_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_business_id_invoice_id_fkey FOREIGN KEY (business_id, invoice_id) REFERENCES public.invoices(business_id, id) ON DELETE CASCADE;


--
-- Name: price_floors price_floors_business_id_variant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.price_floors
    ADD CONSTRAINT price_floors_business_id_variant_id_fkey FOREIGN KEY (business_id, variant_id) REFERENCES public.product_variants(business_id, id) ON DELETE CASCADE;


--
-- Name: pricing_policies pricing_policies_business_id_variant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pricing_policies
    ADD CONSTRAINT pricing_policies_business_id_variant_id_fkey FOREIGN KEY (business_id, variant_id) REFERENCES public.product_variants(business_id, id) ON DELETE CASCADE;


--
-- Name: product_variants product_variants_business_id_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_variants
    ADD CONSTRAINT product_variants_business_id_product_id_fkey FOREIGN KEY (business_id, product_id) REFERENCES public.products(business_id, id) ON DELETE CASCADE;


--
-- Name: products products_business_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;


--
-- Name: style_examples style_examples_business_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.style_examples
    ADD CONSTRAINT style_examples_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;


--
-- Name: subscriptions subscriptions_business_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;


--
-- Name: turns turns_business_id_conversation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turns
    ADD CONSTRAINT turns_business_id_conversation_id_fkey FOREIGN KEY (business_id, conversation_id) REFERENCES public.conversations(business_id, id) ON DELETE CASCADE;


--
-- Name: whatsapp_numbers whatsapp_numbers_business_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.whatsapp_numbers
    ADD CONSTRAINT whatsapp_numbers_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE;


--
-- Name: accounts; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;

--
-- Name: audit_log; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;

--
-- Name: business_users; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.business_users ENABLE ROW LEVEL SECURITY;

--
-- Name: businesses; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.businesses ENABLE ROW LEVEL SECURITY;

--
-- Name: config_proposals; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.config_proposals ENABLE ROW LEVEL SECURITY;

--
-- Name: conversations; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;

--
-- Name: customers; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;

--
-- Name: deals; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.deals ENABLE ROW LEVEL SECURITY;

--
-- Name: handoffs; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.handoffs ENABLE ROW LEVEL SECURITY;

--
-- Name: idempotency_keys; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.idempotency_keys ENABLE ROW LEVEL SECURITY;

--
-- Name: invoices; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;

--
-- Name: knowledge_gaps; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.knowledge_gaps ENABLE ROW LEVEL SECURITY;

--
-- Name: accounts member_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY member_read ON public.accounts FOR SELECT USING ((EXISTS ( SELECT 1
   FROM public.business_users bu
  WHERE ((bu.account_id = accounts.id) AND (bu.business_id = public.current_business_id())))));


--
-- Name: messages; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

--
-- Name: negotiations; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.negotiations ENABLE ROW LEVEL SECURITY;

--
-- Name: offers; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.offers ENABLE ROW LEVEL SECURITY;

--
-- Name: outbox; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.outbox ENABLE ROW LEVEL SECURITY;

--
-- Name: owner_messages; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.owner_messages ENABLE ROW LEVEL SECURITY;

--
-- Name: payments; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

--
-- Name: price_floors; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.price_floors ENABLE ROW LEVEL SECURITY;

--
-- Name: pricing_policies; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.pricing_policies ENABLE ROW LEVEL SECURITY;

--
-- Name: product_variants; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;

--
-- Name: products; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

--
-- Name: style_examples; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.style_examples ENABLE ROW LEVEL SECURITY;

--
-- Name: subscriptions; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

--
-- Name: outbox tenant_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_insert ON public.outbox FOR INSERT WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: audit_log tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.audit_log USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: business_users tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.business_users USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: businesses tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.businesses USING ((id = public.current_business_id())) WITH CHECK ((id = public.current_business_id()));


--
-- Name: config_proposals tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.config_proposals USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: conversations tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.conversations USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: customers tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.customers USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: deals tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.deals USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: handoffs tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.handoffs USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: idempotency_keys tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.idempotency_keys USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: invoices tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.invoices USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: knowledge_gaps tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.knowledge_gaps USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: messages tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.messages USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: negotiations tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.negotiations USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: offers tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.offers USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: owner_messages tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.owner_messages USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: payments tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.payments USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: price_floors tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.price_floors USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: pricing_policies tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.pricing_policies USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: product_variants tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.product_variants USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: products tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.products USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: style_examples tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.style_examples USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: subscriptions tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.subscriptions USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: turns tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.turns USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: whatsapp_numbers tenant_isolation; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation ON public.whatsapp_numbers USING ((business_id = public.current_business_id())) WITH CHECK ((business_id = public.current_business_id()));


--
-- Name: turns; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.turns ENABLE ROW LEVEL SECURITY;

--
-- Name: whatsapp_numbers; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.whatsapp_numbers ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict 0tF4UX3202nT0IA28KBaTr46KfkaCgkDqWKONiyuPdeIqMQcgn6SYn0mJHxm2cB

