#!/usr/bin/env bash
# Regenerates db/schema.sql: a readable snapshot of the schema produced by the migrations (the migrations in
# backend/migrations remain the source of truth). Needs a throwaway Postgres superuser. Usage: scripts/dump_schema.sh
set -euo pipefail
cd "$(dirname "$0")/.."
SUPER="${DEV_PG_SUPERUSER_URL:-postgresql://postgres@127.0.0.1:5432/postgres}"
DB="salesai_schema_dump"
psql "$SUPER" -qc "DROP DATABASE IF EXISTS $DB" -c "CREATE DATABASE $DB"
DBURL="${SUPER%/*}/$DB"
psql "$DBURL" -q -v owner_pw=o -v user_pw=u -v pricing_pw=p -v system_pw=s -f db/bootstrap_roles.sql
OWNER_URL="postgresql://app_owner:o@$(echo "$SUPER" | sed -E 's#.*@([^/]+)/.*#\1#')/$DB"
( cd backend && MIGRATIONS_DIR=migrations .venv/bin/python -c "from salesai.migrate import run_migrations; run_migrations('$OWNER_URL')" )
{
  echo "-- Snapshot of the schema produced by backend/migrations (generated by scripts/dump_schema.sh; do not edit)."
  echo "-- The migrations are the source of truth. Roles are created by db/bootstrap_roles.sql."
  pg_dump "$DBURL" --schema-only --no-owner --no-privileges --no-comments | sed -e '/^SET /d' -e '/^SELECT pg_catalog.set_config/d' -e '/^\\\\/d'
} > db/schema.sql
psql "$SUPER" -qc "DROP DATABASE $DB"
echo "wrote db/schema.sql ($(wc -l < db/schema.sql) lines)"
