# Windows (PowerShell) version of scripts/up.sh: run the whole product on one machine.
# Usage (from the repository folder):   powershell -ExecutionPolicy Bypass -File scripts\up.ps1 -Demo
#   -Demo    also load demo shops and conversations
#   -Down    stop everything
#   -Reset   stop and DELETE the database volume
param([switch]$Demo, [switch]$Down, [switch]$Reset)
$ErrorActionPreference = 'Stop'
Set-Location (Join-Path $PSScriptRoot '..\deploy')
$envFile = '.env'

function Gen([int]$n = 32) {
  $bytes = New-Object byte[] 48
  [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
  (([Convert]::ToBase64String($bytes)) -replace '[/+=]', '').Substring(0, $n)
}

if ($Down)  { docker compose down; exit 0 }
if ($Reset) { docker compose --profile demo --profile redis down -v; Remove-Item -Force -ErrorAction SilentlyContinue $envFile; Write-Host 'reset'; exit 0 }

if (-not (Test-Path $envFile)) {
  $key = New-Object byte[] 32
  [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($key)
  $lines = @(
    '# Generated by scripts/up.ps1. Demo mode: simulated WhatsApp network + deterministic local AI stand-in.',
    'APP_ENV=staging',
    "POSTGRES_PASSWORD=$(Gen)", "APP_OWNER_PASSWORD=$(Gen)", "APP_USER_PASSWORD=$(Gen)", "APP_PRICING_PASSWORD=$(Gen)", "APP_SYSTEM_PASSWORD=$(Gen)",
    "MASTER_KEY=$([Convert]::ToBase64String($key))",
    "JWT_SECRET=$(Gen 48)", "OTP_SECRET=$(Gen 48)", "META_APP_SECRET=$(Gen)", "META_VERIFY_TOKEN=$(Gen 24)",
    'SIMULATOR_ENABLED=true', 'LLM_PROVIDER=local', 'OTP_ACCEPT_ANY=true', 'PAYMENT_PROVIDER=test',
    'OTP_MIN_INTERVAL_S=1', 'OTP_PER_PHONE_PER_HOUR=500', 'OTP_PER_IP_PER_HOUR=2000', 'WEB_PORT=8080'
  )
  # UTF-8 without a byte-order mark, LF line endings (docker compose is strict about both)
  [IO.File]::WriteAllText((Join-Path (Get-Location) $envFile), ($lines -join "`n") + "`n", (New-Object Text.UTF8Encoding($false)))
  Write-Host 'created deploy\.env with fresh secrets'
}

docker compose up -d --build
if ($Demo) { docker compose --profile demo run --rm seed }
Write-Host ''
Write-Host 'Open http://localhost:8080   (app: /app)'
Write-Host 'Demo: any new mobile number signs up with any 6-digit code. Owner +91 99999 00001, operator +91 99999 00000.'
