#!/usr/bin/env bash
# Run the whole product on one machine with one command. Usage:  scripts/up.sh [--demo] [--down] [--reset]
#   --demo   also load demo shops and conversations (so there is something to look at)
#   --down   stop everything
#   --reset  stop and DELETE the database volume
set -euo pipefail
cd "$(dirname "$0")/../deploy"
ENVF=.env
gen() { head -c 32 /dev/urandom | base64 | tr -d '/+=\n' | head -c "${1:-32}"; }
case "${1:-}" in
  --down)  docker compose down; exit 0 ;;
  --reset) docker compose --profile demo --profile redis down -v; rm -f "$ENVF"; echo "reset"; exit 0 ;;
esac
if [ ! -f "$ENVF" ]; then
  cat > "$ENVF" <<ENV
# Generated by scripts/up.sh. Demo mode: simulated WhatsApp network + deterministic local AI stand-in.
APP_ENV=staging
POSTGRES_PASSWORD=$(gen)
APP_OWNER_PASSWORD=$(gen)
APP_USER_PASSWORD=$(gen)
APP_PRICING_PASSWORD=$(gen)
APP_SYSTEM_PASSWORD=$(gen)
MASTER_KEY=$(head -c 32 /dev/urandom | base64)
JWT_SECRET=$(gen 48)
OTP_SECRET=$(gen 48)
META_APP_SECRET=$(gen)
META_VERIFY_TOKEN=$(gen 24)
SIMULATOR_ENABLED=true
LLM_PROVIDER=local
OTP_ACCEPT_ANY=true
PAYMENT_PROVIDER=test
OTP_MIN_INTERVAL_S=1
OTP_PER_PHONE_PER_HOUR=500
OTP_PER_IP_PER_HOUR=2000
WEB_PORT=8080
ENV
  echo "created deploy/.env with fresh secrets"
fi
docker compose up -d --build
if [ "${1:-}" = "--demo" ]; then docker compose --profile demo run --rm seed; fi
echo
echo "Open http://localhost:${WEB_PORT:-8080}   (app: /app)"
echo "Demo logins (the login code appears in the simulated WhatsApp inbox on the sign-in page):"
echo "  owner     +91 99999 00001   operator  +91 99999 00000"
